plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'net.dv8tion:JDA:6.4.1'
    implementation 'fr.citedesiles:cdi2-core-plugin:1.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'fr.citedesiles.discordbot.DiscordBot'
}